package Jvakt;

import java.io.IOException;
import java.net.InetAddress;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.*;
import java.time.*;
import java.security.*;  
import java.math.BigInteger;  
import java.nio.charset.StandardCharsets; 


public class test01 {
	static String database = "jVakt";
	static String dbuser   = "jVakt";
	static String dbpassword = "xz";
	static String dbhost   = "localhost";
	static String dbport   = "5433";
	static String jvhost   = "localhost";
	static String jvport   = "1956";
	static int port ;
	static String agent = null;
	static String DBUrl = "jdbc:postgresql://localhost:5433/Jvakt";
	static Connection conn = null;

	public static void main (String args[]) {
		
	     try 
	        { 
//	    	 https://www.geeksforgeeks.org/sha-256-hash-in-java/   
//	    	 https://stackoverflow.com/questions/32032851/how-to-calculate-hash-value-of-a-file-in-java
	    	 System.out.println("HashCode Generated by SHA-256 for:");  
	  
	            String s1 = "GeeksForGeeks";  
	            System.out.println("\n" + s1 + " : " + toHexString(getSHA(s1)));  
	  
	            String s2 = "hello world";  
	            System.out.println("\n" + s2 + " : " + toHexString(getSHA(s2)));  
	        
	            String s3 = "A";  
	            System.out.println("\n" + s3 + " : " + toHexString(getSHA(s3)));  

	        } 
	        // For specifying wrong message digest algorithms  
	        catch (NoSuchAlgorithmException e) {  
	            System.out.println("Exception thrown for incorrect algorithm: " + e);  
	        }  

	   InetAddress inet;
	   Statement stmt = null;
	   
	   try {
       inet = InetAddress.getLocalHost();
       System.out.println("\n-- Inet: "+inet);

       System.out.println("-- Start consoleHst ");
       
//       String[] par = new String[] { "One", "Two", "Three" };
//       consoleHst.main(par);
//       
       
//       new Thread() {
//           public void run(){
//        	   String[] par = new String[] { "One", "Two", "Three" };
//        	   try {
//        	   consoleHst.main(par);
//        	   } 		catch (IOException e1) {
//    			System.err.println(e1);
//    			System.err.println(e1.getMessage());
//    		}
// 
//           }
//         }.start();

//       Class.forName("org.postgresql.Driver").newInstance();
//		DBUrl = "jdbc:postgresql://"+dbhost+":"+dbport+"/"+database;
//		conn = DriverManager.getConnection(DBUrl,dbuser,dbpassword);
//		conn.setAutoCommit(true);
//
//		String s = new String("select * from status " + 
//				"WHERE state='A' or state = 'D';"); 


		//			System.out.println(s);
//		stmt = conn.createStatement(ResultSet.CONCUR_UPDATABLE,ResultSet.TYPE_FORWARD_ONLY,ResultSet.CLOSE_CURSORS_AT_COMMIT ); 
//		stmt.setFetchSize(1000);
//		ResultSet rs = stmt.executeQuery(s);
//		ResultSet rs;
		
//		LocalDateTime nu = LocalDateTime.now(); // The current date and time

//       Date nux = new Date(rs.getTime("chktim").getTime()  );
       Date nux = new Date(222112000);
       
       Calendar cal = Calendar.getInstance();
//       cal.setTime(rs.getTime("chktim"));
       cal.setTime(nux);
       cal.set(1970, 01, 01, 8, 0, 0);
       System.out.println("-- nux "+nux);
       System.out.println("-- Timme "+cal.get(Calendar.HOUR_OF_DAY)+"    -- MInut "+cal.get(Calendar.MINUTE) + "-- Sekund "+cal.get(Calendar.SECOND));
       
       cal.set(1970, 01, 01, 0, 0, 0);
       java.sql.Time sqlt =  new java.sql.Time( cal.getTime().getTime());
       System.out.println("-- sqlt "+sqlt + "   "+cal.getTime().getTime());
       cal.set(1970, 01, 01, 6, 0, 0);
       sqlt =  new java.sql.Time( cal.getTime().getTime());
       System.out.println("-- sqlt "+sqlt + "   "+cal.getTime().getTime());
       cal.set(1970, 01, 01, 8, 0, 0);
       sqlt =  new java.sql.Time( cal.getTime().getTime());
       System.out.println("-- sqlt "+sqlt + "   "+cal.getTime().getTime());
       
       cal.setTimeInMillis(2696400000L);
       sqlt =  new java.sql.Time( cal.getTime().getTime());
       System.out.println("-- sqlt "+sqlt + "   "+cal.getTime().getTime());

       LocalDateTime nu = LocalDateTime.now(); // The current date and time
       
		cal.set(1970, 01, 01, 6, 0, 0); // only HH:MM:SS is used
//		st.setTime(9, new java.sql.Time( cal.getTime().getTime())); // chktim 06:00:00

//       if (nu.getHour() > nux.getHours() ) {};
//       if (nu.getHour() > rs.getTime("chktim").getHours() ) {};
       
//       Runtime.getRuntime().exec("java -cp \"C:\\Users\\septpadm\\OneDrive - Perstorp Group\\JavaSrc;C:\\Users\\septpadm\\OneDrive - Perstorp Group\\JavaSrc\\postgresql-42.1.3.jar\" Jvakt.consoleHst");
       
       
         System.out.println("-- End console ");

         
   }
   catch (Exception e) { System.out.println(e);  }
   }

	public static byte[] getSHA(String input) throws NoSuchAlgorithmException 
    {  
        // Static getInstance method is called with hashing SHA  
        MessageDigest md = MessageDigest.getInstance("SHA-256");  
  
        // digest() method called  
        // to calculate message digest of an input  
        // and return array of byte 
        return md.digest(input.getBytes(StandardCharsets.UTF_8));  
    } 
    
    public static String toHexString(byte[] hash) 
    { 
        // Convert byte array into signum representation  
        BigInteger number = new BigInteger(1, hash);  
  
        // Convert message digest into hex value  
        StringBuilder hexString = new StringBuilder(number.toString(16)); 
  
        // Pad with leading zeros 
        while (hexString.length() < 32)  
        {  
            hexString.insert(0, '0');  
        }  
  
        return hexString.toString();  
    } 
	
	
}

